### ISSUE TITLE
Problem with _run() function :

### ISSUE THREAD

**Issue by bemichel** [brentp/bsub#10]

**Comment by bemichel** [comment]
Hi,
I test your module (the last version "0.3.5") on the LSF cluster i used to use and I encountered a problem when I am using it (test.py) : 
```python
from bsub import bsub

sub = bsub("some_job", P="9417302F", W="100", n="1", verbose=True)
cmds = """
ls
"""
job = sub(cmds)
print job.job_id
```
and I get the following error :
```shell
test > python test.py 
echo "
ls
date
sleep 3
" | bsub  -e some_job.%J.err -J some_job -o some_job.%J.out -n 1 -P 2417302F -W 100
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    job = sub(cmds)
  File "build/bdist.linux-x86_64/egg/bsub/bsub.py", line 216, in __call__
  File "build/bdist.linux-x86_64/egg/bsub/bsub.py", line 350, in _run
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 35: ordinal not in range(128)
```

I believe that it is a unicode decode error while Popen return an ascii string or there are french accent into it that unicode can not decode. 
So I change it to :
```python
def _run(command, check_str="is submitted"):
    p = sp.Popen(command, shell=True, stdout=sp.PIPE, stderr=sp.PIPE)
    p.wait()
    res = p.stdout.read().strip()
    if isinstance(res, unicode):
        res = res.decode()
    err = p.stderr.read().strip()
    if isinstance(err, unicode):
        err = res.decode() 
    if p.returncode == 255:
        raise BSubJobNotFound(command)
    elif p.returncode != 0:
        if(res): sys.stderr.write(res)
        if(err): sys.stderr.write(err)
        raise BSubException(command + "[" + str(p.returncode) + "]")
    if not (check_str in res and p.returncode == 0):
        raise BSubException(res)
    # could return job-id from here
    return res
```
and it's working ! Do you another way to do it a better way ?

NB : Be aware that I change this line too:
```python
        ...
        if(err): sys.stderr.write(err) ### and not sys.stderr.write(res)
        ...
```

Thanks for this work.
Bertrand.

**Comment by brentp** [comment]
Hi, thanks for reporting. What if instead of the if block you do:

```
res.decode("utf-8", "replace")
```
?

**Comment by bemichel** [comment]
Yes, it works perfectly with your correction.

**Comment by brentp** [comment]
@bemichel could you check the latest commit (tagged to v0.3.6) and make sure it works for you? If so, I'll release to pypi.
